### ISSUE TITLE
create pdf with token, key list and instructions (for teachers)

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#10]

**Comment by jnsdrtlf** [comment]
Basic WeasyPrint functionality has been implement with commit e91d07d7. There is now a command to render a document to a file for development purposes:

```shell
python manage.py print <document> <output>
```

Additionally, the new `gcampus.print` app comes with the functions
 - `render`
 - `as_bytes_io`
 - `as_response`
 - `as_file`
to render and return a document for use in Django views. E-Mail support (#8) is still missing.

**Comment by jnsdrtlf** [comment]
@ax-sc already created a template for the token list.

When testing this template, I noticed a significant delay due to the rather large SVG files. Maybe we should use some high-quality PNGs instead? Then it would be easier to render the document on-the-go instead of using a task queue. What do you think @ax-sc ? Maybe we do not even need the large header but a QR-code + some CSS suffice?

**Comment by ax-sc** [comment]
Thanks for your work in e91d07d7b918c4b68f0c991f261c1e79f8fa0138! The actual template has only been checked in as a placeholder and I have already been working on better (not only in terms of performance) templates locally. Both of the SVG files will be removed (as the header is not print-friendly at all and the QR-code not optimzed yet) and replaced by much smaller files and i will check to possibility to only use PNGs.

**Comment by ax-sc** [comment]
@jnsdrtlf The template has been updated, maybe you could take a look at the performance again? The final PDF should be around 500KB (for 2 pages), the only asset used is a PNG with ~120KB. For the final document, we will for sure need some additional CSS to style the actual content of the page, but I think this shouldn´t have a major effect on the performance.  I am going to work on the styling of the content in the next days, but if you already have some feedback on the layout, i would try to include this in the next iteration.

**Comment by ax-sc** [comment]
The template (`access_course.html`) has been finalized in a3ddb4a496c3995dde92af75f62f25e735bc17b7. It should now be ready to use in the further process. We still need to change the code to include the actual data (which is currently replaced by sample data for testing) and create the document on the request of the user.

**Comment by jnsdrtlf** [comment]
This looks neat! Really liking the design of the document. One question: We've set the maximum number of tokens to `REGISTER_MAX_TOKEN_NUMBER = 50`. How would the page look with 50 tokens? Maybe we have to limit the number of tokens to the number of tokens that we can put onto one page for the sake of convenience?

**Comment by ax-sc** [comment]
Yes, that is one of the minor problematic details of the current layout. It does only work well for up to 30 keys. Maybe with some small improvements we can fit 40 on one page, but setting the max number to 30 should be okay for the moment.

Sidenote: Maybe we should change the name to `REGISTER_MAX_KEY_NUMBER` to not confuse ourselfes with keys and tokens.
