### ISSUE TITLE
report problematic data points

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#24]
- [x] add button to measurement detail page and open form with field for the reason to report the content
- [x] ~send email with report to teacher (?)~
- [x] send email with report to ?@gewaessercampus.de

**Comment by ax-sc** [comment]
> send email with report to teacher (?) 

@nlwach Maybe you could add the option to notify the teacher of the corresponding course as well? This is something we have not discussed earlier, what do you think? (We would need different templates/texts for the mails, but i think it could be useful as some of the reports may be handled by the teachers on their own before we get to it)

**Comment by jnsdrtlf** [comment]
I find it problematic as this would enable anyone to trigger an email which is send to a teacher - even if there might not be a problem. Especially if we send a custom message to the teacher.

I think we should not make teachers responsible to responding to complaints. While they are - to a certain degree - responsible for the content of their students, we should investigate the complaints first and only then contact teachers if there is an issue.

**Comment by jnsdrtlf** [comment]
This however requires us to be respond quickly.

Also note that we currently have a problem with spam on a contact form on our website. I think it is only a matter of time once bots find and abuse the "report problematic data" form 😄.

**Comment by nlwach** [comment]
With [f7ed9af](https://github.com/desklab/gcampus/commit/f7ed9af5377ef99f23b6a30840093d97436b65d8) the main functionality of the report measurement is implemented. 

We might need to reword the possible choices in the dropdown. So far I have
-  Problem with value 
- Problem with note
- Location not on a water
- Location not public
- Name of water does not match location

Can you think of some more problems?

**Comment by ax-sc** [comment]
Looks good to me. Should we add a category for *spam* and another one named *none of the above*?

**Comment by nlwach** [comment]
What do you mean with a category for spam?

I added a category for "Other"

**Comment by ax-sc** [comment]
I was thinking of a a fictional measurement, which has been created with the intention to enter information, that is not correlated with what GewässerCampus is built and used for. Such measurements would have problems with values, notes and possibly also locations at the same time, making it hard to decide between the categories, but as i hope this is unlikely to happen, i´m also fine with summarizing them in the "other" category.
