### ISSUE TITLE
Implement Task Queue for (Scheduled) Automated Tasks

### ISSUE THREAD

**Issue by jnsdrtlf** [desklab/gcampus#32]
Celery is pretty neat and easy to use. It [integrates nicely with django](https://docs.celeryproject.org/en/latest/django/first-steps-with-django.html#using-celery-with-django).

_edit by @ax-sc :_
Overview of actions handled with task queue
- [x] on registration, create a PDF with access keys and course token via WeasyPrint and send the confirmation email with the PDF attached
- [x] Cron job to delete measurements without any data-points after X days.
- [x] deactivate access keys after X days

**Comment by ax-sc** [comment]
I updated your first comment (@jnsdrtlf) to include a list of all actions, which we want to implement with the task queue, to have a better overview of the progress with this issue.
