### ISSUE TITLE
use consistent translations and designations for actions and help texts

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#46]
### Sidebar
- [x] Explore / Erkunden
- [x] All measurements / Alle Messungen
- [x] Analysis / Auswertung
- [x] Course / Kursverwaltung
- [x] Teaching material / Unterrichtsmaterialien
- [x] Report a problem / Problem melden
- [x] About the project / Über das Projekt

### Messung erstellen
- [x] new Measurement / neue Messung (Link mit plus-icon)
- [x] metadata / Metadaten (1. Schritt)
- [x] name / Name
- [x] time / Messzeitpunkt
- [x] location / Ort
- [x] note / Notiz
- [x] Measured values / Messwerte (2. Schritt)
- [x] parameter / Parameter
- [x] note / Notiz

### User-Dropdown
- [x] Course Measurements / Kursmessungen (wenn eingeloggt mit Kursschlüssel)
- [x] Your Measurements / Deine Messungen (wenn eingeloggt mit Zugangscode)
- [x] Login + Logout / Anmelden + Abmelden

### Allgemein
- [ ] Add / Hinzufügen
- [ ] Discard / Abbrechen
- [ ] Close / Schließen
- [ ] Save / Speichern
- [ ] Save and Close / Speichern und Schließen

### Filter
- [ ] Messzeitpunkt liegt vor / liegt nach

### Detailansicht Messung
- [x] Delete / Löschen
- [x] Edit / Bearbeiten
- [x] Download PDF / PDF herunterladen
- [x] measured values / Messwerte
- [x] parameter / Parameter
- [x] value / Wert
- [x] note / Notiz

### Kursverwaltung (war vorher Kursübersicht)
- [x] Course administration / Kursverwaltung
- [x] Course data / Kursdaten
- [x] Access key / Zugangscode
- [x] Course token / Kursschlüssel
- [x] Name of school / Name der Schule
- [x] Name of course / Name des Kurses
- [x] Name of teacher / Name der Lehkraft
- [x] email / E-Mail-Adresse
- [x] (optional) / (optional)
- [x] Options / Optionen
- [x] Deactivate / Deaktivieren
- [x] Activate / Aktivieren
- [x] Login with this access key / Mit diesem Zugangscode anmelden 
- [x] Copy access key / Zugangscode kopieren
- [x] Generate access keys / Zugangscodes erstellen
- [x] Save course overview / Kursübersicht speichern
- [x] Save access keys / Zugangscodes speichern
- [x] Download PDF / PDF herunterladen
- [x] Send to my email / An meine E-Mail-Adresse versenden
- [x] Send email / E-Mail versenden

### Sonstige
- [x] Register / Registrieren

### Registrieren
- [x] Register a new course / Neuen Kurs registrieren (page title)
- [x] Name of school / Name der Schule
- [x] Name of course / Name des Kurses
- [x] Name of teacher / Name der Lehkraft
- [x] email / E-Mail-Adresse
- [x] number of access keys / Anzahl der Zugangscodes

### Anmelden
- [x] Login with access key / Mit Zugangscode anmelden
- [x] Login with course token / Mit Kursschlüssel anmelden
- [x] register a new course / Neuen Kurs registrieren

### Messungen (Liste)
- [ ] Gewässername
- [ ] Ort
- [ ] Name
- [ ] Parameter
- [ ] Messzeitpunkt
- [ ] Bearbeiten (nur Icon?)

**Comment by jnsdrtlf** [comment]
@ax-sc should we keep **Map** and **Measurements** in the sidebar in english too? Or translate it as **Explore** and **All Measurements**?

**Comment by ax-sc** [comment]
I think we should try to be as consistent as possible (also across languages). As i do not see a specific reason to keep **Map** and **Measurements** in favour of **Explore** and **All measurements**, i would prefer the latter.

**Comment by ax-sc** [comment]
I have combined the locales into one file with e54d31c34a5aa3249232855cbf4c9a790770702d. Thus it should now be easier to keep them consistent.
