### ISSUE TITLE
Consistent Timezone use

### ISSUE THREAD

**Issue by nlwach** [desklab/gcampus#48]
Right now we use UTC timezone when localising the time. This leads to the issue that when localising the time (as it is done in the measurement list view when hovering over the time) the displayed time is not the same as the time the measurement was originally conducted. Ideally we would get the timezone from the browser to calculate and display the correct times. I am however not sure if and/or how simple this is realisable.

**Comment by jnsdrtlf** [comment]
According to the [django documentation on time zones](https://docs.djangoproject.com/en/4.0/topics/i18n/timezones):

> Django stores datetime information in UTC in the database, uses time-zone-aware datetime objects internally, and translates them to the end user’s time zone in templates and forms.

and

> Time zone support is disabled by default. To enable it, set USE_TZ = True in your settings file.

I checked the settings and it seems like we enabled time zones:
https://github.com/desklab/gcampus/blob/97414109c3b919b217e49cba2a48c1338dba76bb/gcampus/settings/base.py#L144

According to [*"Selecting the current timezone"*](https://docs.djangoproject.com/en/4.0/topics/i18n/timezones/#selecting-the-current-time-zone), the browser does not inform django which time zone should be selected. Instead, the default time zone `TIME_ZONE` is used. This might require some more work but for the beginning, we could just set `TIME_ZONE` to be * Central European Time*. I am not certain whether this accounts for daylight saving time.

**Comment by jnsdrtlf** [comment]
Maybe the easiest approach would be to have some small JavaScript embedded in every page that checks the browsers time zone with

```javascript
let timeZone = new Intl.DateTimeFormat().resolvedOptions().timeZone
```

and set a cookie with the time zone. When a request is then send to django, the time zone cookie is available in django and can be used [with a middleware](https://docs.djangoproject.com/en/4.0/topics/i18n/timezones/#selecting-the-current-time-zone).

Alternatively, the JavaScript code could also send a `POST` request to some endpoint with the browsers time zone as its payload. This django endpoint would then set time zone for the current session. We could then just remove the script from the base template if the time zone has been set already.
When logging out, the session is deleted. It would be beneficial to save the time zone before reseting the user's session.
