### ISSUE TITLE
Empty popup card in water detail page map

### ISSUE THREAD

**Issue by nlwach** [desklab/gcampus#73]
When clicking on pins in the map of the water detail page, the card appears empty. 
However, the information about the measurement should be displayed.

**Comment by ax-sc** [comment]
Do we want to keep the current behaviour of showing only measurements of the selected water? If not and we do see a benefit in showing all measurements in the water detail map in the same way we do on the main map, we can simply remove the additional parameter of the url used to fetch the additional data for the popup to fix the issue.

https://github.com/desklab/gcampus/blob/3114da69b28e58b9fb85cc7bf2ccf3799fa1f24f/gcampus/core/templates/gcampuscore/sites/detail/water_detail.html#L142

If we don´t want to change the behaviour of the map, the handling of the `detailApiUrl` in `setupCluster()` has to be adapted to handle urls containing a `?` and additional parameters correctly and not just adding a `/` and the `pk`.
https://github.com/desklab/gcampus/blob/3114da69b28e58b9fb85cc7bf2ccf3799fa1f24f/gcampus/map/static_src/js/clustering.js#L298-L329

**Comment by jnsdrtlf** [comment]
I think we should keep the current behaviour. As a fix, I split the URL at the questionmark `?` to drop all URL parameters in 8e892a4 as you suggested.
