### ISSUE TITLE
Missing message modals 

### ISSUE THREAD

**Issue by jnsdrtlf** [desklab/gcampus#74]
The message modals for any action (e.g. logging out, register a course) are missing completely.

**Comment by ax-sc** [comment]
i think they are missing in the production environment as well?

**Comment by jnsdrtlf** [comment]
Fixed in bd6fef1. I haven't quite understood why the toast weren't visible. I had to remove the `position: fixed` style from the parent `div` to make them visible again. I assume something in Bootstrap might have changed that broke our implementation.
