### ISSUE TITLE
use environment variable to define OpenStreetMap server

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#82]
When creating or editing a measurement, no water suggestions are shown (even though the requested water is already in the database) and the overpass API times out repeatedly as well.

@jnsdrtlf Can you have a look at this?

**Comment by jnsdrtlf** [comment]
Experienced this locally as well. I changed the server to the official OpenStreetMap Overpass server. We can do the same in production.

**Comment by jnsdrtlf** [comment]
Unfortunately the setting can not be changed with environment variables:

https://github.com/desklab/gcampus/blob/c60ce26beb7d0407dc3c1d5841c7a0312a008f3a/gcampus/settings/base.py#L204

Let's change it to an environment variable and adjust the server accordingly.

**Comment by ax-sc** [comment]
I agree with changing it to an environment variable, so we are more flexible to change the server when needed. There shouldn´t be any users at the moment, so i think it´s not urgent to release a new version directly as i hope the problems with the current API are just temporary.

Could you reproduce the missing suggestions for waters which are already in our database as well?

**Comment by jnsdrtlf** [comment]
Hm that's odd. Are the geographies of the waters in our database correct (not set to 0,0)?

I'll have a look later today.

**Comment by ax-sc** [comment]
Good point, i recently refreshed my database and did not update the geographies, so that was only a local issue.

**Comment by jnsdrtlf** [comment]
@ax-sc does this mean the error is resolved for waters saved in the local database?

**Comment by ax-sc** [comment]
Yes 👍🏻

**Comment by jnsdrtlf** [comment]
Fixed in 08150f1
