### ISSUE TITLE
create pdf with key and instructions (one page per student)

### ISSUE THREAD

**Issue by ax-sc** [desklab/gcampus#9]

**Comment by ax-sc** [comment]
The templates have been finalized in a3ddb4a496c3995dde92af75f62f25e735bc17b7. It should now be ready to use in the further process. There is one template (`access_student_single.html`) for a pdf with one page (including a single key) and another template (`access_student_combined.html`) for a pdf with one page per key including all keys of a course. We still need to replace some small paragraphs with real content, change the code to include the actual data (which is currently replaced by sample data for testing) and create the document on the request of the user.

**Comment by jnsdrtlf** [comment]
Can this be closed?

**Comment by ax-sc** [comment]
I left it open on purpose as the document(s) cannot be created through the UI yet.
